language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - CONSOLE=2.6.* NETTE=2.4.*
    - CONSOLE=2.6.* NETTE=2.3.*
    - CONSOLE=2.5.* NETTE=2.4.*
    - CONSOLE=2.5.* NETTE=2.3.*
    - CONSOLE=2.4.* NETTE=2.4.*
    - CONSOLE=2.4.* NETTE=2.3.*
    - CONSOLE=2.3.* NETTE=2.2.*

matrix:
  include:
    - php: 5.6
      env: CONSOLE=orig NETTE=orig
    - php: 7.0
      env: CONSOLE=orig NETTE=orig
  exclude:
    - php: 5.5
      env: CONSOLE=2.6.* NETTE=2.4.*
    - php: 5.5
      env: CONSOLE=2.5.* NETTE=2.4.*
    - php: 5.5
      env: CONSOLE=2.4.* NETTE=2.4.*
    - php: 5.4
      env: CONSOLE=2.6.* NETTE=2.4.*
    - php: 5.4
      env: CONSOLE=2.5.* NETTE=2.4.*
    - php: 5.4
      env: CONSOLE=2.4.* NETTE=2.4.*

before_install:
  - travis_retry composer self-update
  - php tests/travis-composer.php

install:
  - travis_retry composer update --no-interaction --prefer-dist

script: vendor/bin/tester ./tests/
